NAV-155-disable-buttons-if-terminus
fjelltopp/navigator_ui pull request #25
Opened 2021-11-26 11:32 UTC by Manoj-nathwani

https://fjelltopp.atlassian.net/browse/NAV-155
- Set `terminus` using `workflow.currentTask.details.terminus`
- If `terminus`  then disable the `taskCompleteCheckbox` and `nextTaskButton` buttons

## Tests output:
```
$ yarn test
yarn run v1.22.17
$ jest
 PASS  lib/actionButtons.test.js
  The "Task Complete" button should
    if the workflow is terminus
      ✓ always return a disabled button with no onClick Action (4 ms)
    if the workflow is not terminus
      If the task isLatestTask in the breadcrumbs
        and is set to manual
          ✓ and is incomplete, should return an enabled unchecked button with the markTaskAsComplete onclick action (1 ms)
        and is set to not manual
          ✓ and is incomplete, should return an enabled unchecked button with the toggleCompleteStateLocally onclick action (1 ms)
      If the task !isLatestTask in the breadcrumbs
        and is set to manual
          ✓ and is incomplete, should return an enabled unchecked button with the markTaskAsComplete onclick action (1 ms)
          ✓ and is complete, should return an enabled checked button with the markTaskAsIncomplete onclick action (1 ms)
        and is set to not manual
          ✓ and is incomplete, should return an disabled unchecked button
          ✓ and is complete, should return an disabled checked button
  The "Prior Task" button should
    If the task is set to manual
      ✓ and if !isOldestTask in the breadcrumbs, should return an enabled button with the getPreviousTask onclick action (1 ms)
      ✓ and if isOldestTask in the breadcrumbs, should return a disabled button
    If the task is not set to manual
      ✓ and if breadcrumbs length > 1, should return an enabled button with the getPreviousTask onclick action
      ✓ and if breadcrumbs length <= 1, should return a disabled button (1 ms)
  The "Next Task" button should
    if the workflow is terminus
      ✓ The "Next Task" button should be disabled (1 ms)
    if the workflow is not terminus
      ✓ If the task isLatestTask in the breadcrumbs, should return an disabled button (1 ms)
      ✓ If the task !isLatestTask in the breadcrumbs, should return an enabled button with the onclick getNextTask action (1 ms)
  The "What's Next" button should
    ✓ If the task is complete, should return an enabled button with the onclick [fetchLatestWorkflowState] actions (1 ms)
    ✓ If the task is incomplete, should return an enabled button with the onclick skipTaskAndFetchLatestWorkflowState actions (1 ms)

Test Suites: 1 passed, 1 total
Tests:       16 passed, 16 total
Snapshots:   0 total
Time:        0.447 s, estimated 1 s
Ran all test suites.
Done in 2.41s.
```

2021-11-29 09:13 UTC, jonathansberry requested changes
Two thoughts:
- Why is the previous task button disabled in your screen shot?  Presumably that is because you are just testing the system with a single complete action in the breadcrumbs? 
- The task complete button I think it should be disabled, with the tool tip, but visually set to "complete" since everything is complete.

2021-11-29 12:16 UTC, Manoj-nathwani commented
> Two thoughts:
> 
> * Why is the previous task button disabled in your screen shot?  Presumably that is because you are just testing the system with a single complete action in the breadcrumbs?
> * The task complete button I think it should be disabled, with the tool tip, but visually set to "complete" since everything is complete.

- Yes, my screenshot is just an example and does not reflect the state of real data
-  ➡️  good point, we should always set the complete checkbox to checked, regardless of workflow state

2021-11-30 07:34 UTC, tomeksabala commented
Fixed a bug and marked task as completed if terminus. I think we can merge it after JB approves.
![image](https://user-images.githubusercontent.com/30174560/144004931-07adfc66-9a21-40dd-95ea-7861fb4eb4ba.png)

2021-11-30 08:49 UTC, Manoj-nathwani commented
Looks good! @tomeksabala have you run a `yarn test` to confirm everything works?

2021-11-30 09:07 UTC, jonathansberry approved these changes

2021-11-30 09:07 UTC, merged