NAV-185-disabled-action-button-tooltips
fjelltopp/navigator_ui pull request #57
Opened 2022-01-05 15:12 UTC by Manoj-nathwani

- https://fjelltopp.atlassian.net/browse/NAV-185

2022-01-05 15:13 UTC, Manoj-nathwani commented
@jonathansberry: Do we ever want to disable the `What's Next?` button if `terminus: true`.
I think we should.

2022-01-05 15:27 UTC, jonathansberry commented
> @jonathansberry: Do we ever want to disable the `What's Next?` button if `terminus: true`. I think we should.

No we don't.  They may have changed something in the underlying data that changes the result of the what's next button.

2022-01-05 15:34 UTC, jonathansberry requested changes
Ok good. Thanks for the quick work.  I've proposed some typo fixing for the tooltip messages. Once those are addressed I am happy to merge. Make sure you take some time to manually test it, since there are no automated tests yet.

2022-01-05 15:34 UTC, jonathansberry commented on lib/actionButtons.js
> +          'Click "What\'s Next ? " to proceed.'
```suggestion
          'Click "What\'s Next?" to proceed.'
```

2022-01-05 15:34 UTC, jonathansberry commented on lib/actionButtons.js
> +    const firstTaskTooltip = ['This is your first task'];
```suggestion
    const firstTaskTooltip = ['This is your first task.'];
```

2022-01-05 15:34 UTC, jonathansberry commented on lib/actionButtons.js
> +            'Click "What\'s Next" once task is complete.',
```suggestion
            'Click "What\'s Next?" once task is complete.',
```

2022-01-05 15:34 UTC, jonathansberry commented on lib/actionButtons.js
> +        tooltip: ['This workflow is now complete']
```suggestion
        tooltip: ['This workflow is now complete.']
```

2022-01-06 10:33 UTC, jonathansberry approved these changes

2022-01-06 10:34 UTC, merged